### ISSUE TITLE
A better way to include plibsys headers?

### ISSUE THREAD

**Issue by dlee992** [Chris3606/plibsys-networking#1]
Chris,
Hello!
I am a newbie in CMake and ddl, and I want to know whether exists a better way to include plibsys headers rather than hard-coding these kinds of stuff?
Thanks for any means of help, for example, a reference link or sth.

**Comment by dlee992** [comment]
Oh, I find a cmake doc says how to use dependency: https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#id1.

**Comment by Chris3606** [comment]
I just saw this now, apologies;

I'll be honest, it's been literally years since I've even looked at this code -- it was created as a demo for a friend's pet project years ago and I haven't touched it since then.  Plibsys has changed pretty significantly since then.  I've also gotten significantly wiser with respect to coding since then.

I believe plibsys itself uses cmake, so arguably the better way to do all this is just use cmake's add_subdirectory functionality, point it at plibsys itself, and have it compile for the platform you're running on.  Otherwise, though, you can detect platform with cmake; it has several constants that are defined (or not) based on what platform you're compiling for: https://cmake.org/cmake/help/latest/variable/WIN32.html

You could use that to point it at the right instance of configured header via `include_directory`.
